/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yeni;

import java.util.ArrayList;
import java.util.Scanner;

/**
 *
 * @author akif
 */
public class pencere extends javax.swing.JFrame {

    /**
     * Creates new form pencere
     */
    String kisiler;
    String dizi[];
    public static ArrayList<Integer> kisileri_bolme_listesi = new ArrayList<>();
    
    public static ArrayList<Integer> grup_list = new ArrayList<>();
    public static    ArrayList<Integer> bindiricegim_grup_list = new ArrayList<>();
      public static  String str_r,str_k,str_n;
      
       
   
          public static   int k;//Kaç kişi enfazla bir seferde binebiliyior
          public static  int R;//Kaç defa çalışacak
          public static   int N;//Grupsayısı
          public static   int toplam_fiyat=0;
        
    public pencere() {
         
        
        initComponents();
        
       
   
     
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_fiyat = new javax.swing.JLabel();
        btn_hesapla = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        et_gruptakikisisayilari = new javax.swing.JLabel();
        et_kackerecaliscak = new javax.swing.JTextField();
        et_kackisibiniyor = new javax.swing.JTextField();
        et_kacgrupvar = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_fiyat.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        txt_fiyat.setText("0");

        btn_hesapla.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_hesapla.setText("HESAPLA");
        btn_hesapla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hesaplaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("FİYAT :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Kaç Kere Çalışacak");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("En Fazla Kaç Kişi Binebiliyor");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Kaç Grup Var");

        et_gruptakikisisayilari.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        et_gruptakikisisayilari.setText("Gruptaki kişi sayılarını boşluk bırakarak yazınız");

        et_kackerecaliscak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                et_kackerecaliscakActionPerformed(evt);
            }
        });

        et_kackisibiniyor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                et_kackisibiniyorActionPerformed(evt);
            }
        });

        et_kacgrupvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                et_kacgrupvarActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel5.setText("TL");
        jLabel5.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_fiyat, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(et_gruptakikisisayilari)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(245, 245, 245)))
                                        .addComponent(jLabel4))
                                    .addGap(0, 0, 0)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(et_kackisibiniyor, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                        .addComponent(et_kacgrupvar)
                                        .addComponent(et_kackerecaliscak))))
                            .addComponent(btn_hesapla, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(et_kackerecaliscak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(et_kackisibiniyor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(et_kacgrupvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(et_gruptakikisisayilari))
                .addGap(38, 38, 38)
                .addComponent(btn_hesapla, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_fiyat)
                    .addComponent(jLabel5))
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_hesaplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hesaplaActionPerformed
  
           
        str_r = (et_kackerecaliscak.getText().toString());
     R = Integer.parseInt(str_r);
       str_k = (et_kackisibiniyor.getText().toString());
        k = Integer.parseInt(str_k);
          str_n = (et_kacgrupvar.getText().toString());
        N = Integer.parseInt(str_n); 

            kisiler=jTextField1.getText().toString();
    
        
         dizi = kisiler.split(" ");
         
         for (int i = 0; i < dizi.length; i++) {
            grup_list.add(Integer.parseInt(dizi[i]));
        }
        
       
       
        int sayac=0;
        int calisma_sayisi=1;
       
        //algoritma başlangıcı
        for (int i = 0; i < grup_list.size(); i+=sayac) {
       if(calisma_sayisi<=R){
           
           
             //her binecek grubun başında parayı sıfırla
            toplam_fiyat=0;
            
                   if(grup_list.get(i)<=k){
                   
                       toplam_fiyat = grup_list.get(i);
                       grup_list.add(grup_list.get(i)); //binen kişi tekrar ekle
                       sayac=1;
                     }   
                   if(grup_list.get(i)+grup_list.get(i+1)<=k){
                       
                     toplam_fiyat += grup_list.get(i+1);
                     grup_list.add(grup_list.get(i+1)); //binen kişiyi tekrar ekle
                  sayac=2;
                   }
                   if(grup_list.get(i)+grup_list.get(i+1)+grup_list.get(i+2)<=k){
                     sayac=3;
                     toplam_fiyat += grup_list.get(i+2);
                     grup_list.add(grup_list.get(i+2)); //binen kişiyi tekrar ekle
                   
                       
                   }if(grup_list.get(i)+grup_list.get(i+1)+grup_list.get(i+2)+grup_list.get(i+3)<=k){
                     sayac=4;
                     toplam_fiyat += grup_list.get(i+3);
                     grup_list.add(grup_list.get(i+3)); //binen kişiyi tekrar ekle
                   
                       
                   }else{
                       
                       bindiricegim_grup_list.add(toplam_fiyat);
                       calisma_sayisi++;
                       
                       }
       }else{
       
       break;
       }
        }//for döngü
        
        int fyt=0;
        for (int i = 0; i < bindiricegim_grup_list.size(); i++) {
            fyt += bindiricegim_grup_list.get(i);
        }
        
        txt_fiyat.setText(""+fyt);
        
        
    }//GEN-LAST:event_btn_hesaplaActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
     
    
   
      // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void et_kackerecaliscakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_et_kackerecaliscakActionPerformed

        

// TODO add your handling code here:
    }//GEN-LAST:event_et_kackerecaliscakActionPerformed

    private void et_kackisibiniyorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_et_kackisibiniyorActionPerformed

 
        // TODO add your handling code here:
    }//GEN-LAST:event_et_kackisibiniyorActionPerformed

    private void et_kacgrupvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_et_kacgrupvarActionPerformed

      
        // TODO add your handling code here:
    }//GEN-LAST:event_et_kacgrupvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pencere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pencere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pencere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pencere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pencere().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hesapla;
    private javax.swing.JLabel et_gruptakikisisayilari;
    private javax.swing.JTextField et_kacgrupvar;
    private javax.swing.JTextField et_kackerecaliscak;
    private javax.swing.JTextField et_kackisibiniyor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel txt_fiyat;
    // End of variables declaration//GEN-END:variables
}
